"""empty message

Revision ID: 7ab9358f8459
Revises: 913dc6454bac
Create Date: 2022-05-17 23:44:23.531124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab9358f8459'
down_revision = '913dc6454bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('eye_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'eye_color')
    # ### end Alembic commands ###
